OpenFeign/querydsl

pom.xml, querydsl-apt/pom.xml, querydsl-core/src/main/java/com/querydsl/core/alias/AliasFactory.java, querydsl-core/src/main/java/com/querydsl/core/alias/PropertyAccessInvocationHandler.java, querydsl-examples/querydsl-example-jpa-guice/pom.xml, querydsl-hibernate-search/pom.xml, querydsl-jpa-codegen/pom.xml, querydsl-jpa/pom.xml, querydsl-spatial/pom.xml
Using code from this PR
https://github.com/querydsl/querydsl/pull/3307
=> Improve Bytebuddy usage

pom.xml, querydsl-apt/src/main/onejar.xml, querydsl-jpa/src/main/assembly-hibernate.xml, querydsl-jpa/src/main/assembly.xml
Follow up of PR https://github.com/OpenFeign/querydsl/pull/262
=> Remove cglib assembly references

querydsl-sql/src/main/java/com/querydsl/sql/ddl/ColumnData.java, querydsl-sql/src/main/java/com/querydsl/sql/ddl/CreateTableClause.java, querydsl-sql/src/main/java/com/querydsl/sql/ddl/DropTableClause.java, querydsl-sql/src/main/java/com/querydsl/sql/ddl/ForeignKeyBuilder.java, querydsl-sql/src/main/java/com/querydsl/sql/ddl/ForeignKeyData.java, querydsl-sql/src/main/java/com/querydsl/sql/ddl/IndexData.java, querydsl-sql/src/main/java/com/querydsl/sql/ddl/KeyData.java, querydsl-sql/src/main/java/com/querydsl/sql/ddl/PrimaryKeyData.java
See https://github.com/querydsl/querydsl/issues/3295
The DDL package somehow got stranded among the tests. Have copied it back over into main. Where did the actual tests go?
=>  Reintroduce DDL to SQL module @monst

pom.xml, querydsl-libraries/querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java, querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/JPABase.java
Port of https://github.com/querydsl/querydsl/pull/3712
@MelleD I hope you don't mind if I get a release out with your fixes.
=> Fix using multi query hints @MelleD

querydsl-libraries/querydsl-sql/src/main/java/com/querydsl/sql/ProjectableSQLQuery.java
=> Update from(Expression<?> arg) to public visibility

querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/DefaultEntitySerializer.java
=> Suppress "this-escape" warning in auto-generated entities

querydsl-libraries/querydsl-sql/src/test/java/com/querydsl/sql/MergeUsingBase.java
A small unit test for PR https://github.com/OpenFeign/querydsl/pull/393
=> Add unit test for merge using on statement schema fix

querydsl-codegen/src/main/java/com/querydsl/codegen/DefaultEntitySerializer.java
(cherry picked from commit f4018e75a75a75bc3be713c0be112c95af2350a2)
related to #387
=> Suppress "this-escape" warning in auto-generated entities (#388)

querydsl-tooling/querydsl-codegen-utils/src/main/java/com/querydsl/codegen/utils/Symbols.java, querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/BeanSerializer.java, querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/DefaultEmbeddableSerializer.java, querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/DefaultEntitySerializer.java, querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/DefaultProjectionSerializer.java, querydsl-tooling/querydsl-sql-codegen/src/main/java/com/querydsl/sql/codegen/MetaDataSerializer.java
=> Suppress this-escape warning in all auto-generated entities more properly

querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/types/QBeanFieldAccessTest.java, querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/types/QBeanTest.java, querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/util/MultiIteratorTest.java, querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/HibernateBase.java, querydsl-libraries/querydsl-mongodb/src/test/java/com/querydsl/mongodb/MongodbQueryTest.java, querydsl-libraries/querydsl-mongodb/src/test/java/com/querydsl/mongodb/document/MongodbQueryTest.java, querydsl-libraries/querydsl-r2dbc/src/test/java/com/querydsl/r2dbc/UnionBase.java, querydsl-libraries/querydsl-sql/src/test/java/com/querydsl/sql/SelectBase.java, querydsl-libraries/querydsl-sql/src/test/java/com/querydsl/sql/UnionBase.java, querydsl-tooling/querydsl-codegen-utils/src/test/java/com/querydsl/codegen/utils/model/TypeAdapterTest.java
$ mvn org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:2.14.0-SNAPSHOT -Drewrite.activeRecipes=org.openrewrite.java.testing.assertj.Assertj
=> Cleanup isEqualTo(boolean)

querydsl-apt/src/main/java/com/querydsl/apt/SimpleTypeVisitorAdapter.java
Porting https://github.com/querydsl/querydsl/pull/3738
=> Deprecated type visitor @kamilkrzywanski

querydsl-core/src/main/java/com/querydsl/core/types/ConstructorExpression.java, querydsl-core/src/test/java/com/querydsl/core/types/ConstructorExpressionTest.java
I've ported changes found in our company implementation.
https://github.com/aasyspl/querydsl
=> Querydsl 5.0.0 serialization fix

querydsl-core/src/main/java/com/querydsl/core/group/GroupByGenericCollection.java, querydsl-core/src/main/java/com/querydsl/core/group/GroupByGenericMap.java, querydsl-core/src/main/java/com/querydsl/core/group/GroupByIterate.java, querydsl-core/src/main/java/com/querydsl/core/group/GroupByMap.java, querydsl-core/src/main/java/com/querydsl/core/util/TupleUtils.java, querydsl-jpa/src/test/java/com/querydsl/jpa/HibernateBase.java
from https://github.com/aasyspl/querydsl
fixes  https://github.com/querydsl/querydsl/issues/3264 (checked with issuer example)
=> The transform method throws a ClassCastException when working with joinFetch since 4.4.0

querydsl-examples/querydsl-example-kotlin-codegen/pom.xml, querydsl-examples/querydsl-example-kotlin-codegen/src/main/kotlin/com/querydsl/examples/kotlin/converter/MapConverter.kt, querydsl-examples/querydsl-example-kotlin-codegen/src/main/kotlin/com/querydsl/examples/kotlin/entity/ExampleEntity.kt
Added example of an entity using the Any type
=> Added example of using Any in kotlin codegen

pom.xml, querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/SimpleDTOProjection.java, querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/DefaultQueryMetadataTest.java, querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/ReactiveQueryExecution.java, querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/SimpleDTOProjectionTest.java, querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/group/GroupByIterateTest.java, querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/group/GroupByListTest.java, querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/group/GroupByMapTest.java
Description:
This pull request introduces a new feature to the QueryDSL project: `SimpleDTOProjection`. This feature allows for simplified DTO projections by dynamically mapping fields from the entity to the DTO based on matching field names.
- **Added `SimpleDTOProjection`** class to support dynamic DTO field mapping.
- **Implemented constructor and expression handling** to create instances of DTOs with matching field names automatically.
- Enhanced flexibility in projecting data into DTOs without the need for explicit field-by-field mapping.
- The `SimpleDTOProjection` class dynamically maps fields from the provided entity to the specified DTO type.
- It eliminates the need to manually specify each field during projection, reducing boilerplate code and potential errors.
- Added …
=> Add SimpleDTOProjection for dynamic DTO field mapping

pom.xml, querydsl-tooling/pom.xml, querydsl-tooling/querydsl-kotlin-codegen/pom.xml, querydsl-tooling/querydsl-ksp-codegen/pom.xml, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/KspArgParser.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/KspSettings.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/Naming.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QProperty.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QPropertyType.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryDslProcessor.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryDslProcessorProvider.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModel.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelExtractor.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelRenderer.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/SimpleType.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/TypeExtractor.kt, querydsl-tooling/querydsl-ksp-codegen/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider, querydsl-tooling/querydsl-ksp-codegen/src/test/kotlin/RenderTest.kt
@velo 
As agreed upon this PR does not contain example project as that will be coming in another PR later.
You mentioned that we could try to preserve git history but since there has been multiple edits and changes of build systems i'm no longer sure if there would be a benefit to that. So i'm doing this as a single squashed commit.
We can add more tests later.
If i figure out how to use kotlin-compile-testing-ksp with Kotlin 2.0 then we can also test [Entity classes] -> [Intermediate models]
It's missing changes to the readme file, i think the readme file should probably mention that KSP is supported and say something about how people can use it with gradle.
=> KSP module

querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/dsl/BooleanExpression.java, querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/dsl/ComparableExpression.java, querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/dsl/ComparableExpressionBase.java, querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/dsl/DateExpression.java, querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/dsl/DateTimeExpression.java, querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/dsl/EnumExpression.java, querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/dsl/NumberExpression.java, querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/dsl/StringExpression.java, querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/types/dsl/TimeExpression.java, querydsl-libraries/querydsl-core/src/test/java/com/querydsl/core/types/ExpressivityTest.java
=> Fix coalesce - requires exact type issue #683

.github/workflows/sync-master-to-development.yml
This PR syncs changes from master into querydsl-7.0
=> Sync master into querydsl-7.0

querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/AbstractModule.java, querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/AnnotationHelper.java, querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/BeanSerializer.java, querydsl-tooling/querydsl-sql-codegen/src/main/java/com/querydsl/sql/codegen/MetaDataExporter.java, querydsl-tooling/querydsl-sql-codegen/src/main/java/com/querydsl/sql/codegen/OrdinalPositionComparator.java, querydsl-tooling/querydsl-sql-codegen/src/main/java/com/querydsl/sql/codegen/ant/AntMetaDataExporter.java, querydsl-tooling/querydsl-sql-codegen/src/main/java/com/querydsl/sql/codegen/support/TypeMapping.java
=> Cleanup mainly for querydsl-sql-codegen

.github/workflows/codeql-analysis.yml
=> fix #871 - bump codeQl to v3

querydsl-tooling/querydsl-ksp-codegen/readme.md
Adds readme.md into the project.
Mostly a copy-paste from my original repo.
=> Add readme for ksp
