OpenFeign/querydsl

querydsl-sql/src/main/java/com/querydsl/sql/types/UtilUUIDType.java

mssql-jdbc knows how to return UUID, but if you don't specify a type, it returns String

Make UtilUUIDType work more reliably

---

querydsl-sql/src/main/java/com/querydsl/sql/SQLBaseListener.java
querydsl-sql/src/main/java/com/querydsl/sql/SQLListener.java
querydsl-sql/src/main/java/com/querydsl/sql/SQLListenerAdapter.java
querydsl-sql/src/main/java/com/querydsl/sql/SQLListeners.java
querydsl-sql/src/main/java/com/querydsl/sql/SQLSerializer.java
querydsl-sql/src/main/java/com/querydsl/sql/SQLTemplates.java
querydsl-sql/src/main/java/com/querydsl/sql/dml/SQLMergeClause.java
querydsl-sql/src/main/java/com/querydsl/sql/dml/SQLMergeUsingCase.java
querydsl-sql/src/main/java/com/querydsl/sql/dml/SQLMergeUsingClause.java
querydsl-sql/src/test/java/com/querydsl/sql/MergeBase.java
querydsl-sql/src/test/java/com/querydsl/sql/SQLListenersTest.java
querydsl-sql/src/test/java/com/querydsl/sql/TestLoggingListener.java

Proposal for addition for merge using syntax related to https://github.com/querydsl/querydsl/issues/2520
Few notes:
*    This changes interfaces, japicmp-maven-plugin will complain
*    Merge using query works also with latest versions of H2 and PostgreSQL, however bumping versions results in other tests breaking
*    In case of Oracle it currently produces Caused by: java.sql.SQLSyntaxErrorException: ORA-00969: missing ON keyword. Reason being it doesn't put "as" between subquery and its alias, not sure how to fix nicely.
Copy of https://github.com/querydsl/querydsl/pull/3625

Merge using extension 

---

querydsl-codegen/src/main/java/com/querydsl/codegen/GenericExporter.java

Class#getConstructors haven't defined order of array of constructors. 
we run query-dsl-maven plugin that generates classes via GenericExporter and then we format them with Eclipse Formatter. 
Between several executions JVM returns some constructor in different order. 
This is attempt to make it somehow sorted.

Sort constructors in generated classes based on constructor toString method

---

querydsl-libraries/querydsl-spatial/src/main/java/com/querydsl/spatial/hibernate/HibernateSpatialSupport.java
querydsl-libraries/querydsl-spatial/src/test/java/com/querydsl/spatial/hibernate/HibernateSpatialSupportTest.java

As the representation of the operations were doing an equal true (boolean check), the DB engine is not able to use the spatial index, and instead of performing the intersects with the entities using the spatial index and comparing only the ones indicated by this one, was applying the intersects operation to all the entities.
How was discovered?
While migrating my application from native spatial queries to querydsl-spatial I found a big downgrade on the performance. Analysing the differences between the native queries that I had and the ones generated by querydsl-spatial, I was able to indentify that queryDSL spatial was adding for most of the operations that I was interested on an = true clause. It is not needed and this comparison makes the db engine to not to use the spatial index on …

Fixing performance issue related with querydsl spatial on hibernate.

---

querydsl-libraries/querydsl-r2dbc/src/main/java/com/querydsl/r2dbc/AbstractR2DBCQuery.java
querydsl-libraries/querydsl-r2dbc/src/test/java/com/querydsl/r2dbc/SelectBase.java
querydsl-libraries/querydsl-sql/src/main/java/com/querydsl/sql/AbstractSQLQuery.java
querydsl-libraries/querydsl-sql/src/main/java/com/querydsl/sql/Configuration.java
querydsl-libraries/querydsl-sql/src/test/java/com/querydsl/sql/SelectBase.java

@nicofabre I replicated https://github.com/querydsl/querydsl/pull/3716 here
Add com.querydsl.sql.StatementOptions filed into Configuration object so that it can be used when a new Sql Query is created (via the Sql Query's configuration field and the configuration's statementOptions field) in order to configure the default settings for the JDBC statement used by a Sql Query.
Make the AbstractSQLQuery.setStatementOptions returning the query in order to allow method chaining.
Add AbstractSQLQuery.fetchSize method to set the JDBC fetch size (via setStatementOptions) to be used by the underlying JDBC Statement.

com.querydsl.sql.StatementOptions - Enable global settings and method chaining @nicofabre

---

querydsl-tooling/querydsl-apt/src/main/java/com/querydsl/apt/TypeExtractor.java
querydsl-tooling/querydsl-apt/src/test/java/com/querydsl/apt/domain/p1/SEntity1.java

@cigaly I replicated your fix https://github.com/querydsl/querydsl/pull/3692 here, should be released shortly
Records were first time introduced as preview feature in Java SE 14 & 15, and as completed feature in Java SE 16, almost three years ago. Hibernate is supporting records as embeddables since version 6 (see, for example, [article by Thorben Janssen](https://thorben-janssen.com/java-records-embeddables-hibernate/))
Sadly, Java records are still not supported in Querydsl APT 5.1.0.
Change to support records is trivial.since they can (mostly) be treated in a same way as "normal" classes.

Support Java 16+ records in querydsl-apt @cigaly

---

.circleci/config.yml

SQL server tests were unreliable, failing with timeouts after 12 minutes. 
Trying newer version to see if problem goes away

Update SQL server image to 2022-latest

---

.circleci/config.yml
docker-compose.yml
querydsl-libraries/querydsl-sql/pom.xml
querydsl-libraries/querydsl-sql/src/test/java/com/querydsl/sql/Connections.java

Attempt to speed up build by changing oracle version
At present talks 11 minutes to run all oracle tests

bump oracle version

---

querydsl-libraries/querydsl-sql/src/main/java/com/querydsl/sql/SQLSerializer.java

Make dmlWithSchema be true while serializing ON condition for MERGE <TABLE> USING ... ON ... so that the TABLE would have schema set correctly in the statement. This is necessary if default schema of connection is not the one where the TABLE is and also allows overriding schema using querydsl configuration.
Also remove pointless extra line change.

Use dmlWithSchema also for on statement in merge-using-query, remove extra line change

---

.mvn/jvm.config
pom.xml
querydsl-libraries/querydsl-sql-spatial/pom.xml
querydsl-libraries/querydsl-sql-spatial/src/main/java/com/querydsl/sql/spatial/JtsGeometryType.java
querydsl-libraries/querydsl-sql-spatial/src/main/java/com/querydsl/sql/spatial/PostGISTemplates.java

Add support for Postgis JTS

---

.circleci/config.yml
pom.xml

Unable to upload -SNAPSHOTs with nexus-staging-maven-plugin
Change to only use plugin on releases, which are working fine

Build is failing due to some bug on nexus-staging-maven-plugin

---

querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/DefaultEntitySerializer.java

Solve the problem of ambiguous reference to StringTemplate on jdk21. fix #476

Explicit reference to StringTemplate

---

querydsl-libraries/querydsl-kotlin/pom.xml
querydsl-tooling/querydsl-codegen-utils/pom.xml
querydsl-tooling/querydsl-codegen-utils/src/main/java/com/querydsl/codegen/utils/AbstractCodeWriter.java
querydsl-tooling/querydsl-codegen-utils/src/main/java/com/querydsl/codegen/utils/JDKEvaluatorFactory.java
querydsl-tooling/querydsl-codegen-utils/src/main/java/com/querydsl/codegen/utils/SimpleCompiler.java
querydsl-tooling/querydsl-codegen-utils/src/test/java/com/querydsl/codegen/utils/AnnotationTest.java
querydsl-tooling/querydsl-codegen-utils/src/test/java/com/querydsl/codegen/utils/JDKEvaluatorFactoryTest.java
querydsl-tooling/querydsl-codegen-utils/src/test/java/com/querydsl/codegen/utils/SimpleCompilerTest.java
querydsl-tooling/querydsl-codegen/pom.xml

@velo 
The AnnotationTest test case was not performed properly, so it was changed to run normally. 
For test cases Via StringWriter Syntax to check whether a specific string matches an expected string. In particular, w.toString().trim() checks for a match to a certain format in an annotated string.
However, we confirmed that it was not performing normally as shown in the picture and modified the test case.
as-is 
to-be

Fix AnnotationTest Class Test Case

---

querydsl-core/src/main/java/com/querydsl/core/group/GroupByList.java
querydsl-core/src/test/java/com/querydsl/core/group/GroupByListTest.java

Another one ported change, also done by querydsl - remove dependency, but this one solution seems be more clear

Delete dependency on elements order from list transformation

---

README.md

@velo 
hello 
README.md contains querydsl url, which is a previous project, but I am trying to change it to the example url of the current project.

Change incorrectly entered URL in document

---

querydsl-tooling/querydsl-ksp-codegen/pom.xml
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QPropertyType.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryDslProcessor.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModel.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelExtractor.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelRenderer.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelType.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/SimpleType.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/TypeExtractor.kt
querydsl-tooling/querydsl-ksp-codegen/src/test/kotlin/RenderTest.kt

As mentioned these are the changes.
Fixing incremental processing support required some larger changes.
Also includes fix for as crash that would happen when using NumberPath with Kotlin types in certain operations during a query.
The test code needed some way to reference KSFile objects, although these are actually not used in the generation itself but must be linked sothat KSP knows when to reprocess the file.
I used mockk to represent these objects in the code, it's a common Kotlin library for mocks.
Not sure if you would have preferred for  me to use some other java library for this?

Incremental processing support for ksp

---

querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/Cat.kt
querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/CatType.kt
querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/Person.kt
querydsl-examples/querydsl-example-ksp-codegen/src/test/kotlin/Tests.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/TypeExtractor.kt

When using nullable types in JPA Entity fields, the type determination code was throwing exceptions. This change creates a local version of the KSType.toClassName() function which gets the ClassName while ignoring the KSType's nullability and parameterization. It also ensures that the ClassName returned does not include a nullability modifier as it previously did with Enums.

Kotlin KSP Nullability Fix

---

querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryDslProcessor.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModel.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelExtractor.kt
querydsl-tooling/querydsl-ksp-codegen/src/test/kotlin/RenderTest.kt

The `containingFile` of `KSClassDeclaration` is nullable. Update the processing to handle a null containingFile. 
I was able to pull, modify, and build the project artifacts. This change fixes the NullPointerException (my local project build now fully completes) and I am able to see the generated Q entities from the external library. Both my Child class entity and Parent Entity in the external library are generated. 
Run build to completion (`mvn -Pquickbuild,all clean install`), pulled in artifacts to my project, built & ran without issues. 
Please let me know if `master` is the correct branch to get a quick fix out. Thanks!

Fix NPE in ksp processing (#862)

---

querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryDslProcessor.kt

- Follow up on @IceBlizz6 comment from PR https://github.com/OpenFeign/querydsl/pull/865 
Alot of details in the comments of that PR, but after the NPE from #862 was fixed an additional cross-project rebuild issue was introduced now that the build is getting through the NPE. This was not related to the NPE fix, but as far as I can tell it is just a lacking feature in querydsl ksp processing. 
The change moves responsibilities of generating Q classes to each individual module, whether that module is in a local project or a library dependency. If a module is expecting a class (like a base entity `@MappedSuperclass`) to be used in a client project, it must incorporate KSP processing and package the generated Q class in its artifact. To achieve this, the superclasses are still stored as a …

Fix file generation issue on rebuild (#862)

---

querydsl-tooling/querydsl-kotlin-codegen/src/main/kotlin/com/querydsl/kotlin/codegen/Extensions.kt
querydsl-tooling/querydsl-kotlin-codegen/src/main/kotlin/com/querydsl/kotlin/codegen/KotlinEntitySerializer.kt

Refer to issue https://github.com/OpenFeign/querydsl/issues/891 for the complete report.
This PR handles the issue by adding out keywords to the generated Q-classes when they are needed.

Properly handle parameterized mapped superclass issue #891

---

querydsl-tooling/querydsl-codegen-utils/src/main/java/com/querydsl/codegen/utils/model/SimpleType.java

@velo check and merge it if you agree :)

Porting old fix for issue for StringIndexOutOfBoundsException

---

querydsl-libraries/querydsl-jpa/src/main/java/com/querydsl/jpa/JPQLSerializer.java
querydsl-libraries/querydsl-jpa/src/main/java/com/querydsl/jpa/JPQLTemplates.java
querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/JPQLSerializerTest.java

This PR addresses an issue where enums used in CaseBuilder within QueryDSL are serialized as bind parameters (?) or full class paths (e.g., com.example.JobFunction.MANAGER), causing Hibernate to fail with a ConversionException: Could not determine ValueMapping for SqmParameter. This behavior disrupts compatibility with Hibernate, especially in CASE WHEN expressions.
The goal of this change is to serialize enums as string literals (e.g., 'MANAGER') in JPQL, ensuring Hibernate can process them correctly without binding issues.
**1. JPQLSerializer Modification:**
Updated visitConstant to handle Enum instances by delegating to visitLiteral, preventing them from being treated as bind parameters.
Before: Enums were passed to super.visitConstant(), resulting in ? parameters.
After: Enums are …

Fix Enum Serialization in CaseBuilder for Hibernate Compatibility

---

pom.xml
querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/PersonDTO.kt
querydsl-examples/querydsl-example-ksp-codegen/src/test/kotlin/Tests.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryDslProcessor.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelRenderer.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelType.kt
querydsl-tooling/querydsl-ksp-codegen/src/test/kotlin/RenderTest.kt

fixes #996 
Could you please check this feature at @IceBlizz6 if possible?
Thank you.

Enable @QueryProjection annotation support for KSP.

---

pom.xml
querydsl-libraries/pom.xml
querydsl-libraries/querydsl-core/src/main/java/com/querydsl/core/annotations/QueryProjection.java
querydsl-tooling/querydsl-apt/src/main/java/com/querydsl/apt/AbstractQuerydslProcessor.java
querydsl-tooling/querydsl-apt/src/main/java/com/querydsl/apt/TypeElementHandler.java
querydsl-tooling/querydsl-apt/src/test/java/com/querydsl/apt/GenericExporterTest.java
querydsl-tooling/querydsl-apt/src/test/java/com/querydsl/apt/domain/QueryProjectionBuilderTest.java
querydsl-tooling/querydsl-apt/src/test/java/com/querydsl/apt/domain/QueryProjectionBuilderTestEntity.java
querydsl-tooling/querydsl-codegen-utils/src/main/java/com/querydsl/codegen/utils/CodeWriter.java
querydsl-tooling/querydsl-codegen-utils/src/main/java/com/querydsl/codegen/utils/JavaWriter.java
querydsl-tooling/querydsl-codegen-utils/src/main/java/com/querydsl/codegen/utils/ScalaWriter.java
querydsl-tooling/querydsl-codegen-utils/src/main/java/com/querydsl/codegen/utils/model/Constructor.java
querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/DefaultProjectionSerializer.java
querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/GenericExporter.java

- You can now define multiple `@QueryProjection(useBuilder = true, builderName = "...")` constructors per DTO.
- Each builder will be uniquely named inside the Q class and exposed via static factory methods.
- Advantages of { concise syntax, no explicit `new`,  IDE friendly}
1. Fully backward compatible — default remains constructor-style
2. No need to manually define a builder in the DTO
3. Improves readability and safety in complex DTO projections
4. All builder method arguments are Expression<?>, just like in constructor-style projections
To support multiple builder configurations, `@QueryProjection(useBuilder = true)` now requires a non-empty `builderName`.  
This helps prevent name collisions when generating builder classes and factory methods.
```java
public class …
```

feat(@QueryProjection): support builder-based Q class generation

---

querydsl-examples/querydsl-example-ksp-codegen/build.gradle.kts
querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/Dog.kt
querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/Tag.kt
querydsl-examples/querydsl-example-ksp-codegen/src/test/kotlin/Tests.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/TypeExtractor.kt

Starting from Hibernate 6, the @JdbcTypeCode annotation allows developers to explicitly specify the JDBC type for entity fields. 
For example :
```kotlin
@JdbcTypeCode(SqlTypes.JSON)
@Column(columnDefinition = "json")
val tag: Tag
```
However, the current implementation of querydsl-ksp-codegen does not recognize this annotation. When an entity field is annotated with @JdbcTypeCode, the code generator throws an exception and **fails the entire Q-class generation** at compile time
```
IllegalStateException: Type was not recognised, This may be an entity that has not been annotated with @Entity, or maybe you are using javax instead of jakarta.
```
This is not just a misclassification — the code generation fails entirely, making the project unbuildable if such annotations are present.
- …

querydsl-ksp-codegen: Support @JdbcTypeCode in KSP code generation

---

querydsl-libraries/querydsl-jpa/src/main/java/com/querydsl/jpa/JPQLSerializer.java
querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/JPAQueryConverterCollectionContainsTest.java
querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/domain/Alchemist.java
querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/domain/PotionEffect.java
querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/domain/PotionEffectSetConverter.java

**Related Issue(s):** [#173 querydsl/querydsl ](https://github.com/querydsl/querydsl/issues/3618) , [#377 openfeign/querydsl](https://github.com/OpenFeign/querydsl/issues/377)
When using QueryDSL's `collection.contains(element)` method on a Java `Collection`-typed entity attribute that is mapped to a basic database type (e.g., `String`, `TEXT`) via a JPA `@Converter`, QueryDSL currently generates a standard JPQL `MEMBER OF` clause (often via an internal `Ops.IN` to `JPQLOps.MEMBER_OF` translation).
Historically, some older Hibernate versions might have been less strict in validating this JPQL against such converted attributes, leading some users (like H-Lo in issue #3618, #377) to believe this pattern "worked." However, as pointed out by contributors like OrangeDog, and in line with JPA …

Fix: Improve handling of `contains()` on JPA collections mapped with `@Converter` to basic types

---

querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/Bear.kt
querydsl-examples/querydsl-example-ksp-codegen/src/test/kotlin/Tests.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryDslProcessor.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModel.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelExtractor.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/TypeExtractor.kt
querydsl-tooling/querydsl-ksp-codegen/src/test/kotlin/RenderTest.kt

This pull request solves the issue that was reported in my original repository earlier this week.
https://github.com/IceBlizz6/querydsl-ksp/issues/9
Currently this code
```kotlin
data class PersonClassConstructorDTO @QueryProjection constructor(
val id: Int,
val name: String,
) {
var age: Int = 0
}
```
Becomes
```kotlin
public class QPersonClassConstructorDTO(
id: Expression<Int>,
name: Expression<String>,
age: Expression<Int>,
) : ConstructorExpression<PersonClassConstructorDTO>(PersonClassConstructorDTO::class.java, arrayOf(kotlin.Int::class.java, kotlin.String::class.java, kotlin.Int::class.java), id, name, age)
```
Which is incorrect as it should only include properties from the constructor.
For reference kapt will produce this:
```java …
```

Exclude properties in QueryProjection outside constructor

---

querydsl-examples/querydsl-example-ksp-codegen/build.gradle.kts
querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/Geolocation.kt
querydsl-examples/querydsl-example-ksp-codegen/src/test/kotlin/Tests.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/TypeExtractor.kt

This PR is attempting to solve #1255 
Currently KSP module will throw exception when it encounters an arbitrary type without hibernate annotations, because it believes this is invalid and will alert the user to make the correct configuration.
But there seems to exist cases where arbitrary types are allowed (possibly through plugins?).
This PR adds a fallback where it uses ComparablePath if the type implements Compararable interface and otherwise it uses SimplePath.

Add fallback for unknown types in KSP

---

querydsl-libraries/querydsl-jpa/src/main/java/com/querydsl/jpa/HQLTemplates.java
querydsl-libraries/querydsl-jpa/src/main/java/com/querydsl/jpa/JPQLSerializer.java
querydsl-libraries/querydsl-jpa/src/main/java/com/querydsl/jpa/JPQLTemplates.java
querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/HibernateBase.java
querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/JPQLSerializerTest.java
querydsl-libraries/querydsl-jpa/src/test/java/com/querydsl/jpa/JPQLTemplatesTest.java

This PR addresses a long-standing limitation in QueryDSL where LIMIT and OFFSET modifiers were ignored when used within subqueries. This change enables full subquery modifier support specifically for Hibernate users while maintaining backward compatibility and JPQL standard compliance for other JPA providers.
**Related Issue**: This resolves the subquery modifier limitation reported in [querydsl/querydsl#3224](https://github.com/querydsl/querydsl/issues/3224)
Previously, when users applied `.limit()` or `.offset()` to subqueries, modifiers were silently ignored during query serialization. This was particularly frustrating for Hibernate users since Hibernate 6.0+ natively supports LIMIT/OFFSET in subqueries, but QueryDSL wasn't utilizing this capability.
**Example of previous behavior:** …

Add support for subquery modifiers (LIMIT/OFFSET) in Hibernate

---

querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/QueryModelExtractor.kt
querydsl-tooling/querydsl-ksp-codegen/src/test/kotlin/RenderTest.kt

When migrating from KAPT to KSP, inner class naming conventions differ:
- KAPT: `QOuterClass_InnerClass` 
- KSP: `QInnerClass`
This breaks existing code that relies on KAPT naming conventions.
Modified `QueryModelExtractor.queryClassName()` to:
1. Traverse parent class hierarchy using `generateSequence`
2. Collect all class names from inner to outer
3. Join with underscore separator to match KAPT behavior
- **Fixed**: Inner class naming now matches KAPT exactly
- **Added**: Comprehensive test coverage for nested scenarios
- **Maintained**: Backward compatibility for top-level classes
- ✅ Single level inner class: `OuterClass.InnerClass` → `QOuterClass_InnerClass`
- ✅ Multi-level nesting: `A.B.C` → `QA_B_C`  
- ✅ Top-level classes unchanged: `TopLevel` → `QTopLevel`
- ✅ Custom …

Fix inner class naming in KSP to match KAPT behavior

---

querydsl-examples/querydsl-example-ksp-codegen/build.gradle.kts
querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/MyShape.kt
querydsl-examples/querydsl-example-ksp-codegen/src/test/kotlin/Tests.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/SimpleType.kt
querydsl-tooling/querydsl-ksp-codegen/src/test/kotlin/RenderTest.kt

KSP will correctly process spatial types in entities.
Solves #1375

Support spatial types for KSP

---

querydsl-libraries/querydsl-r2dbc/src/main/java/com/querydsl/r2dbc/AbstractR2DBCQuery.java
querydsl-libraries/querydsl-r2dbc/src/main/java/com/querydsl/r2dbc/R2DBCConnectionProvider.java
querydsl-libraries/querydsl-r2dbc/src/test/java/com/querydsl/r2dbc/Connections.java

issue: https://github.com/OpenFeign/querydsl/issues/352
- add overridable release hook for connection cleanup
- expose withConnection/withConnectionMany wrappers using usingWhen
- provide factory method that opens and closes ConnectionFactory connections

feat: add managed connection helpers to provider

---

querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/Email.kt
querydsl-examples/querydsl-example-ksp-codegen/src/main/kotlin/com/querydsl/example/ksp/Person.kt
querydsl-examples/querydsl-example-ksp-codegen/src/test/kotlin/Tests.kt
querydsl-tooling/querydsl-ksp-codegen/src/main/kotlin/com/querydsl/ksp/codegen/TypeExtractor.kt

resolves #1403 
Fixed codegen error when processing Kotlin value class columns by extracting their underlying wrapped type.
Modified `TypeExtractor.kt` to detect value classes.

Support underlying type extraction for Kotlin value classes in KSP codegen
